In [1]:
import nltk

In [2]:
#vectoriser and cosine siilarity
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
sen1=["No money is not everything. Because cannot buy all the things. Money cannot buy happiness, friends etc. Money can buy only the things but not the happiness. we can take people in our side with the power of money but when we are right than people will follow us. If we have the power of money than people will respect us in front but they will abuse us on our back"]
sen2=["Money if utilized in wrong way or for selfish purpose than money cannot give you a real happiness. Money should not control you i.e. you should not become a puppet which is being controlled by money. You should always take care that money should not have any effect on your relationships."]

In [4]:
# create the transform
vectorizer = CountVectorizer(stop_words='english')
# tokenize and build vocab
vectorizer.fit(sen1)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [5]:
# summarize
print(vectorizer.vocabulary_)

{'money': 5, 'buy': 1, 'things': 10, 'happiness': 4, 'friends': 3, 'people': 6, 'power': 7, 'right': 9, 'follow': 2, 'respect': 8, 'abuse': 0}


In [6]:
# encode document
vector = vectorizer.transform(sen1)

In [7]:
# summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())
vec1=vector.toarray()

(1, 11)
<class 'scipy.sparse.csr.csr_matrix'>
[[1 3 1 1 2 5 3 2 1 1 2]]


In [8]:
print(vectorizer.vocabulary_)

{'money': 5, 'buy': 1, 'things': 10, 'happiness': 4, 'friends': 3, 'people': 6, 'power': 7, 'right': 9, 'follow': 2, 'respect': 8, 'abuse': 0}


In [9]:
#vectorise second document
vector = vectorizer.transform(sen2)
print(vector.toarray())
vec2=vector.toarray()

[[0 0 0 0 1 5 0 0 0 0 0]]


In [10]:
#finding cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vec1,vec2)

array([[0.68359907]])

In [11]:
cosine_similarity(vec1,vec1)

array([[1.]])

In [12]:
##RESULT
##Here the 2 documents we provided are having 68 as cosine similarity therefor it is closer to 1 than 0 hence this documents can be said to SIMILAR means the vectors are not perpendicular and parallel BUT CLOSER TO PARALLEL)

##rule1:if the cosine similarity is 1 ,then the agngles value is 0 degree and the vectors are said to be parallel
##rule2:if the cosine value is 0 and value of the angle is 90 degrees ,then the vectors are said to be perpendicular